"""End-to-end (ERT outcome) against its two comparators on identical rows.

strict_endtoend_refit_ert.py rebuilds all five stages per origin under the ERT
v16 outcome and saves per-row predictions. This scores its rank-mean blend on
exactly the rows it produced and, on those same rows, the shared-representation
framework and the four-polyarchy baseline from strict_ert_sensitivity.py, then
forms the paired country-clustered differences. It exists so that the numbers
in Section 5.3 and passport C28 are regenerated by a script and not by hand.

Outputs robustness/strict_endtoend_ert_comparison.csv.
"""

import os

import numpy as np
import pandas as pd
from scipy.stats import rankdata
from sklearn.metrics import average_precision_score, roc_auc_score

OUT = os.path.dirname(os.path.abspath(__file__))
SEED, N_BOOT = 20260905, 2000


def blend(e):
    b = e.pivot_table(index=["origin", "country_name", "y"], columns="learner", values="p").reset_index()
    acc = np.zeros(len(b))
    for L in ("gb", "rf", "lr"):
        v = b[L].fillna(b[L].median()).values
        r = np.zeros(len(v))
        for o in b.origin.unique():
            m = (b.origin == o).values
            r[m] = rankdata(v[m]) / m.sum()
        acc += r
    b["blend"] = acc / 3
    return b


def paired(y, pa, pb, c):
    rng = np.random.default_rng(SEED)
    u = np.unique(c)
    idx = {k: np.where(c == k)[0] for k in u}
    da, dp = [], []
    for _ in range(N_BOOT):
        j = np.concatenate([idx[k] for k in rng.choice(u, len(u), replace=True)])
        if y[j].sum() < 3 or y[j].sum() == len(j):
            continue
        da.append(roc_auc_score(y[j], pa[j]) - roc_auc_score(y[j], pb[j]))
        dp.append(average_precision_score(y[j], pa[j]) - average_precision_score(y[j], pb[j]))
    f = lambda a: (round(float(np.mean(a)), 4), round(float(np.percentile(a, 2.5)), 4),
                   round(float(np.percentile(a, 97.5)), 4))
    return f(da), f(dp)


def main():
    b = blend(pd.read_csv(os.path.join(OUT, "strict_endtoend_refit_ert.csv")))
    s = pd.read_csv(os.path.join(OUT, "strict_ert_sensitivity_predictions.csv"))
    m = b.merge(s, left_on=["country_name", "origin"], right_on=["country_name", "year"], suffixes=("", "_s"))
    rows = []
    for name, col in [("end_to_end", "blend"), ("shared_representation", "p_framework"),
                      ("four_polyarchy", "p_poly4")]:
        rows.append({"model": name, "n": len(m), "n_pos": int(m.y.sum()),
                     "base_rate": round(float(m.y.mean()), 4),
                     "auc_roc": round(roc_auc_score(m.y, m[col]), 4),
                     "auc_pr": round(average_precision_score(m.y, m[col]), 4)})
        print(f"  {name:<24} AUC {rows[-1]['auc_roc']:.3f}  AP {rows[-1]['auc_pr']:.3f}")
    for name, col in [("end_to_end_minus_shared", "p_framework"),
                      ("end_to_end_minus_four_polyarchy", "p_poly4")]:
        (ma, la, ha), (mp, lp, hp) = paired(m.y.values, m.blend.values, m[col].values, m.country_name.values)
        rows.append({"model": name, "n": len(m), "n_pos": int(m.y.sum()),
                     "base_rate": round(float(m.y.mean()), 4),
                     "auc_roc": ma, "auc_roc_lo": la, "auc_roc_hi": ha,
                     "auc_pr": mp, "auc_pr_lo": lp, "auc_pr_hi": hp})
        print(f"  {name:<32} dAUC {ma:+.3f} [{la:+.3f}, {ha:+.3f}]   dAP {mp:+.3f} [{lp:+.3f}, {hp:+.3f}]")
    pd.DataFrame(rows).to_csv(os.path.join(OUT, "strict_endtoend_ert_comparison.csv"), index=False)
    print(f"\nrows {len(m)}  positives {int(m.y.sum())}\nWrote strict_endtoend_ert_comparison.csv")


if __name__ == "__main__":
    main()
